#########################################
# OresomeCoin                           #
# An OresomeCraft global economy plugin #
#########################################

mysql:
  host: localhost
  port: '3306'
  database: minecraft
  username: root
  password: password